"""Renamed Metadata to ImageMetadata

Revision ID: ad74e05eed11
Revises: 95cc51972a12
Create Date: 2025-03-01 01:18:51.230455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad74e05eed11'
down_revision = '95cc51972a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('metadata')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_extension', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('file_extension')

    op.create_table('metadata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='metadata_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
